---
version: "3.7"
services:
  jenkins:
    extra_hosts:
    - host.docker.internal:host-gateway
    build: config/
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/jcasc
      JAVA_OPTS: >-
        -Djenkins.install.runSetupWizard=false
        -Dhudson.model.UsageStatistics.disabled=true
    volumes:
      - type: volume
        source: jenkins
        target: /var/jenkins_home
      - type: bind
        source: ./config
        target: /var/jenkins_home/config
        read_only: true
      - type: bind
        source: ./config/jenkins.yml
        target: /var/jenkins_home/jcasc/jenkins.yml
        read_only: true
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
volumes:
  jenkins:
    driver: local

networks:
  jenkins:
    driver: bridge
